### ISSUE TITLE
Bots shouldn't deactivate this quickly.

### ISSUE THREAD

**Issue by HappySquid25** [robot-rumble/backend#2]
8 out of the top 10 bots are inactive. This makes the population be too small for a good elo ranking to establish.
I don't think bots should therefore disable after only 14 days of no new commits.
Another option would be to have inactive bots still be challenged. They wouldn't challenge other bots every 12 hours but they could still be the target of a challenge.

**Comment by outkine** [comment]
Thank you so much for reporting! Trying out a fix with https://github.com/robot-rumble/backend/commit/0b9f057cbc1cbdba41ee94cfd030a04ccbf2579d.
