### ISSUE TITLE
Saving a bot gives a 400 error

### ISSUE THREAD

**Issue by mousetail** [robot-rumble/backend#3]
Seems saving bots no longer works. 

Endpoint: `POST https://robotrumble.org/api/update-robot-code/282`

I see the following response:

```json
{"code":["This field is required"]}
```

Additionally, no error is shown on the client side which made me think the bot had been saved. I lost some improvements in my bot this way.

**Comment by outkine** [comment]
Thank you so much for reporting, and I'm sorry that some of your changes were lost! This should be fixed now. I recently pushed a UI rewrite, so please feel free to open an issue for anything else that is off
